"""core application schema

Revision ID: 31c336437812
Revises: 1406e74c56f2
Create Date: 2026-09-23 22:23:42.994900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31c336437812'
down_revision: Union[str, None] = '1406e74c56f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.Enum('risk_score', 'customer_report', 'analyst_request', name='trigger_type'), nullable=False),
    sa.Column('trigger_text', sa.Text(), nullable=False),
    sa.Column('flagged_txn_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('input_risk_score', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed_fraud', 'closed_legitimate', 'escalated', name='case_status'), nullable=True),
    sa.Column('verdict', sa.Enum('fraud', 'legitimate', 'uncertain', name='verdict'), nullable=True),
    sa.Column('fraud_probability', sa.Float(), nullable=True),
    sa.Column('pattern', sa.Enum('card_testing', 'card_not_present_fraud', 'card_not_present_new_device', 'out_of_region_use', 'account_takeover', 'undocumented', 'none', name='pattern'), nullable=True),
    sa.Column('pattern_description', sa.Text(), nullable=False),
    sa.Column('first_suspicious_txn_id', sa.String(length=32), nullable=True),
    sa.Column('exposure_usd', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('written_to_graph', sa.Boolean(), nullable=False),
    sa.Column('graph_case_id', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_card_id'), 'cases', ['card_id'], unique=False)
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_cases_customer_id'), 'cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cases_flagged_txn_id'), 'cases', ['flagged_txn_id'], unique=False)
    op.create_table('closed_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('outcome', sa.Enum('confirmed_fraud', 'cleared', name='prior_outcome'), nullable=False),
    sa.Column('pattern', sa.Enum('card_testing', 'card_not_present_fraud', 'card_not_present_new_device', 'out_of_region_use', 'account_takeover', 'undocumented', 'none', name='pattern'), nullable=False),
    sa.Column('first_fraud_txn_id', sa.String(length=32), nullable=True),
    sa.Column('txn_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('n_txns', sa.Integer(), nullable=False),
    sa.Column('exposure_usd', sa.Float(), nullable=False),
    sa.Column('connected_card_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('actions_taken', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('report_filed', sa.Boolean(), nullable=False),
    sa.Column('analyst_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closed_cases_card_id'), 'closed_cases', ['card_id'], unique=False)
    op.create_index(op.f('ix_closed_cases_case_id'), 'closed_cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_closed_cases_customer_id'), 'closed_cases', ['customer_id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('route', sa.Enum('auto', 'L1', 'L2', name='approval_route'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_rule_id'), 'policy_rules', ['rule_id'], unique=False)
    op.create_table('action_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('action', sa.Enum('ALLOW_TRANSACTION', 'DECLINE_TRANSACTION', 'MONITOR_CARD', 'MONITOR_CONNECTED_CARDS', 'WARN_CUSTOMER', 'VERIFY_WITH_CUSTOMER', 'STEP_UP_AUTH', 'BLOCK_CARD', 'BLOCK_ALL_CARDS', 'GENERATE_REPORT', 'CREATE_CASE', 'FILE_REPORT', 'ESCALATE_TO_ANALYST', 'CLOSE_NO_FRAUD', name='action_type'), nullable=False),
    sa.Column('route', sa.Enum('auto', 'L1', 'L2', name='approval_route'), nullable=False),
    sa.Column('state', sa.Enum('RECOMMENDED', 'HUMAN_APPROVAL_REQUIRED', 'AUTHORIZED', 'EXECUTABLE', 'EXECUTED', 'REJECTED', 'FAILED', name='action_state'), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_executions_case_id'), 'action_executions', ['case_id'], unique=False)
    op.create_index(op.f('ix_action_executions_execution_id'), 'action_executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_action_executions_idempotency_key'), 'action_executions', ['idempotency_key'], unique=True)
    op.create_table('case_connected_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'card_id', name='uq_case_connected_card')
    )
    op.create_index(op.f('ix_case_connected_cards_card_id'), 'case_connected_cards', ['card_id'], unique=False)
    op.create_index(op.f('ix_case_connected_cards_case_id'), 'case_connected_cards', ['case_id'], unique=False)
    op.create_table('case_connected_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('device_profile', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'device_profile', name='uq_case_connected_device')
    )
    op.create_index(op.f('ix_case_connected_devices_case_id'), 'case_connected_devices', ['case_id'], unique=False)
    op.create_table('case_similar_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('prior_case_id', sa.String(length=32), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'prior_case_id', name='uq_case_similar_prior_case')
    )
    op.create_index(op.f('ix_case_similar_cases_case_id'), 'case_similar_cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_similar_cases_prior_case_id'), 'case_similar_cases', ['prior_case_id'], unique=False)
    op.create_table('case_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'transaction_id', name='uq_case_transaction')
    )
    op.create_index(op.f('ix_case_transactions_case_id'), 'case_transactions', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_transactions_transaction_id'), 'case_transactions', ['transaction_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('graph', 'document', 'customer', 'external', name='evidence_source'), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('entity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=True)
    op.create_table('evidence_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('customer_validation', 'step_up_auth', 'analyst_info', name='evidence_request_type'), nullable=False),
    sa.Column('asked_after_step', sa.Integer(), nullable=False),
    sa.Column('assumed_response', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'responded', 'expired', name='evidence_request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_requests_case_id'), 'evidence_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_requests_request_id'), 'evidence_requests', ['request_id'], unique=True)
    op.create_table('investigation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='run_status'), nullable=False),
    sa.Column('stop_reason', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('latency_s', sa.Float(), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_runs_case_id'), 'investigation_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_investigation_runs_run_id'), 'investigation_runs', ['run_id'], unique=True)
    op.create_table('next_best_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.Enum('initial', 'final', name='action_phase'), nullable=False),
    sa.Column('action', sa.Enum('ALLOW_TRANSACTION', 'DECLINE_TRANSACTION', 'MONITOR_CARD', 'MONITOR_CONNECTED_CARDS', 'WARN_CUSTOMER', 'VERIFY_WITH_CUSTOMER', 'STEP_UP_AUTH', 'BLOCK_CARD', 'BLOCK_ALL_CARDS', 'GENERATE_REPORT', 'CREATE_CASE', 'FILE_REPORT', 'ESCALATE_TO_ANALYST', 'CLOSE_NO_FRAUD', name='action_type'), nullable=False),
    sa.Column('route', sa.Enum('auto', 'L1', 'L2', name='approval_route'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('policy_rule', sa.String(length=16), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_next_best_actions_case_id'), 'next_best_actions', ['case_id'], unique=False)
    op.create_table('sar_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('file', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_amount_usd', sa.Float(), nullable=False),
    sa.Column('activity_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('action_execution_id', sa.Integer(), nullable=True),
    sa.Column('route', sa.Enum('auto', 'L1', 'L2', name='approval_route'), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_execution_id'], ['action_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_approval_id'), 'approvals', ['approval_id'], unique=True)
    op.create_index(op.f('ix_approvals_case_id'), 'approvals', ['case_id'], unique=False)
    op.create_table('investigation_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['investigation_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_steps_run_id'), 'investigation_steps', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_steps_run_id'), table_name='investigation_steps')
    op.drop_table('investigation_steps')
    op.drop_index(op.f('ix_approvals_case_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_approval_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_table('sar_reports')
    op.drop_index(op.f('ix_next_best_actions_case_id'), table_name='next_best_actions')
    op.drop_table('next_best_actions')
    op.drop_index(op.f('ix_investigation_runs_run_id'), table_name='investigation_runs')
    op.drop_index(op.f('ix_investigation_runs_case_id'), table_name='investigation_runs')
    op.drop_table('investigation_runs')
    op.drop_index(op.f('ix_evidence_requests_request_id'), table_name='evidence_requests')
    op.drop_index(op.f('ix_evidence_requests_case_id'), table_name='evidence_requests')
    op.drop_table('evidence_requests')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_case_transactions_transaction_id'), table_name='case_transactions')
    op.drop_index(op.f('ix_case_transactions_case_id'), table_name='case_transactions')
    op.drop_table('case_transactions')
    op.drop_index(op.f('ix_case_similar_cases_prior_case_id'), table_name='case_similar_cases')
    op.drop_index(op.f('ix_case_similar_cases_case_id'), table_name='case_similar_cases')
    op.drop_table('case_similar_cases')
    op.drop_index(op.f('ix_case_connected_devices_case_id'), table_name='case_connected_devices')
    op.drop_table('case_connected_devices')
    op.drop_index(op.f('ix_case_connected_cards_case_id'), table_name='case_connected_cards')
    op.drop_index(op.f('ix_case_connected_cards_card_id'), table_name='case_connected_cards')
    op.drop_table('case_connected_cards')
    op.drop_index(op.f('ix_action_executions_idempotency_key'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_execution_id'), table_name='action_executions')
    op.drop_index(op.f('ix_action_executions_case_id'), table_name='action_executions')
    op.drop_table('action_executions')
    op.drop_index(op.f('ix_policy_rules_rule_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_closed_cases_customer_id'), table_name='closed_cases')
    op.drop_index(op.f('ix_closed_cases_case_id'), table_name='closed_cases')
    op.drop_index(op.f('ix_closed_cases_card_id'), table_name='closed_cases')
    op.drop_table('closed_cases')
    op.drop_index(op.f('ix_cases_flagged_txn_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_customer_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_card_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###